site_name: Torque 6
theme: readthedocs
pages:
- Home: index.md
- Assets: assets.md
- Materials: 
    - Overview: materials/overview.md
    - Root Nodes: materials/rootnodes.md
    - Input Nodes: materials/inputnodes.md
    - Math Nodes: materials/mathnodes.md
- Scene:
    - Overview: scene/overview.md
    - Features: scene/features.md
    - Objects: scene/objects.md