language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenal-dev libsdl-dev libxft-dev

before_script:
  chmod +x ./build/genie_linux

script:
  make -R -C ./build release64

branches:
  only:
    - master
